server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    context-path: /reed

book:
  author: reed
  price: 19

cupSize: B
spring:
  rabbitmq:
    host: 47.101.47.253
    port: 5672
    username: reed
    password: reed
    listener:
        concurrency: 10    #并发消费者的初始化值
        max-concurrency: 20   #并发消费者的最大值

        prefetch:    #每个消费者每次监听时可拉取处理的消息数量


  #  jpa:
#    hibernate:
#      ddl-auto: create
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.101.47.253:3306/yiliao?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: reedfan1991
    url: jdbc:mysql://localhost:3306/yiliao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root



  mail:
    host: smtp.163.com
    username: m18915228146@163.com
    password: reed1991
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000




  redis:
    host: 47.101.47.253
    port: 6379
    password: P@ssword1991
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #  mybatis主配置文件所在路径
  mapper-locations: classpath:mybatis/mapper/*.xml  #  所有的mapper映射文件
  type-aliases-package: com.ustc.reed.pojo                       # 定义所有操作类的别名所在包


upload-path: /Users/qufan/Downloads/pictest


security:
  basic:
    enabled: true

reed:
  security:
    browser:
      loginPage: /demo-signIn.html



#   设置日志级别和日志路径
#logging:
#  file: /Users/qufan/Documents/log/sb01.log
#  level:
#    com:
#      ustc:
#        reed: DEBUG


async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 5
      queue_capacity: 99999
      name:
        prefix: async-service-




